### ISSUE TITLE
mimic the new forums scheme

### ISSUE THREAD

**Issue by macMikey** [miyako/language-4dproject#2]
the forums scheme is really sharp, especially with dark reader in safari
<img width="884" alt="Screen Shot 2020-06-18 at 10 26 09" src="https://user-images.githubusercontent.com/10867016/85032995-6c413680-b14e-11ea-961b-e143be48d8c1.png">

i like it better than the atom scheme.

**Comment by miyako** [comment]
I don't understand what you mean by "mimic the **scheme**".

Do you mean, the **colour** scheme?
 
Then change the Atom **theme**..

This, and other language-* repository defines the language **parser**.

**Comment by macMikey** [comment]
sorry, i haven't hacked in on atom.  i assumed there was a theme that was tied to the grammar, somewhere.
the other languages that we program in that use atom all are themed differently, so i figured that was something you set.

**Comment by miyako** [comment]
You can also edit the CSS directly.

https://flight-manual.atom.io/using-atom/sections/basic-customization/
